import React, { useState } from "react";
import Head from "next/head";
import { checkClientMoney, currency } from "../helpers";
import { CurrencyCard, Input } from "../conponents";

export default function Home() {
	const aRollOfMoney = 100;
	const [value, setValue] = useState(0);
	const [showData, setShowData] = useState(false);
	const [hasMoreOptions, setHasMoreoptions] = useState(false);

	const submitHandler = (e) => {
		e.preventDefault();

		if (checkClientMoney(value)) {
			let allMoney = [];
			let amount = value;

			currency.forEach((item) => {
				if (amount <= item?.key * aRollOfMoney && amount >= item?.key) {
					allMoney = [...allMoney, { ...item, count: Math.floor(amount / item?.key) }];
					amount -= Math.floor(amount / item?.key) * item?.key;
					console.log("item", item);
				} else {
					return; // continue
				}
			});

			setShowData(allMoney);
		} else {
			alert("Kechirasiz bizda yetarli mablag' mavjud emas)");
		}
	};

	return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className="py-5">
				<form className="row g-2 g-md-3 g-xl-4" onSubmit={submitHandler}>
					<div className="col-12 col-xl-8">
						<Input value={value} onChange={(e) => setValue(e)} />
					</div>
					<div className="col-12 col-sm-6 col-xl-2 align-self-end">
						<button className="btn w-100 btn-primary">submit</button>
					</div>
					<div className="col-12 col-sm-6 col-xl-2 align-self-end">
						<button className="btn w-100 btn-secondary" onClick={() => setHasMoreoptions((p) => !p)}>
							Options
						</button>
					</div>

					<div className="col-12">
						{hasMoreOptions && (
							<>
								<p>{value}</p>
							</>
						)}
					</div>
				</form>
			</header>

			<main>
				<div className="row g-2 g-md-3 g-xl-4">
					{showData?.length
						? showData?.map((item) => (
								<div key={item?.id} className="col-12 col-md-6 col-lg-3">
									<CurrencyCard {...item} name={item.key} />
								</div>
						  ))
						: null}
				</div>
			</main>
		</div>
	);
}
